//
//  Orders.swift
//  YaleGrill
//
//  Created by Phil Vasseur on 1/5/17.
//  Copyright © 2017 Phil Vasseur. All rights reserved.
//


import Foundation
import UIKit
import Firebase

class Orders : NSObject {
    var userID: String!
    var orderID: String!
    var name: String!
    var foodServing: String!
    var options: [String: Bool]?
    var orderNum: Int?
    var grill : String!
    
    private struct DatabaseKeys {
        static let name = "name"
        static let foodServing = "foodServing"
        static let orderID = "orderID"
        static let userID = "userID"
        static let orderNum = "orderNum"
        static let grill = "grill"
        static let options = "options"
    }
    
    
    //Creates a new Orders object
    init(_userID: String,_name : String, _foodServing : String, _options: [String: Bool]? = nil, _orderID : String? = nil, _orderNum : Int? = nil, _grill : String) {
        self.userID = _userID
        let uuid = UUID().uuidString
        let index = uuid.index(uuid.startIndex, offsetBy: 8)
        //unique grorderID is generated by the current time stamp in nanoseconds and then the first 7 characters of a UUID
        self.orderID = _orderID ?? "\(String(Date().ticks))-\(uuid.substring(to: index))"
        self.name = _name
        self.foodServing = _foodServing
        self.options = _options
        self.orderNum = _orderNum
        self.grill = _grill
    }
    
    //Returns an Orders object from a firebase JSON
    convenience init(orderID: String, json : [String : AnyObject]){
        let userID = json[DatabaseKeys.userID] as! String
        let name = json[DatabaseKeys.name] as! String
        let foodServing = json[DatabaseKeys.foodServing] as! String
        let options = json[DatabaseKeys.options] as? [String : Bool]
        let orderNum = json[DatabaseKeys.orderNum] as? Int
        let grill = json[DatabaseKeys.grill] as! String
        self.init(_userID: userID, _name: name, _foodServing: foodServing, _options: options, _orderID : orderID, _orderNum: orderNum, _grill : grill)
        
    }
    
    //Inserts a new order into fireBase database
    func insertIntoDatabase(){
        let currentOrder = Database.database().reference().child("Orders").child(orderID)
        currentOrder.setValue(convToJSON())
        
        //Inserts orderID/OrderStatus/OrderPushToken into Grills active orders
        let grillOrderInfo: [String: AnyObject] = [
            Constants.orderStatus : 0 as AnyObject,
            "pushToken": Messaging.messaging().fcmToken as AnyObject]
        Database.database().reference().child(Constants.grills).child(grill).child(Constants.orders).child(self.orderID).setValue(grillOrderInfo)
        
        
        //Inserts OrderID into Users active orders
        let cUserId = GIDSignIn.sharedInstance().currentUser.userID!
        Database.database().reference().child(Constants.users).child(cUserId).child(Constants.activeOrders).child(self.orderID).setValue(grill)
        
    }
    
    //Changes current Orders object into a json object to be uploaded to firebase
    private func convToJSON() -> [String : AnyObject?] {
        let jsonObject: [String: AnyObject?] = [
            DatabaseKeys.name : name as AnyObject,
            DatabaseKeys.foodServing: foodServing as AnyObject,
            DatabaseKeys.userID: userID as AnyObject,
            DatabaseKeys.grill : grill as AnyObject,
            DatabaseKeys.options : options as AnyObject
        ]
        return jsonObject
    }
    
}
