//
//  Orders.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit
import AWSDynamoDB
import Firebase

class Orders {
    var databaseRef = FIRDatabase.database().reference()
    
    var userID: String?
    var orderID: String?
    var name: String?
    var foodServing: String?
    var bunSetting: String?
    var cheeseSetting: String?
    var sauceSetting: String?
    var lettuceSetting: String?
    var tomatoSetting: String?
    var orderStatus: Int?
    var orderLocation: Int?
    
    private struct DatabaseKeys {
        static let foodServing = "foodServing"
        static let bunSetting = "bunSetting"
        static let cheeseSetting = "cheeseSetting"
        static let sauceSetting = "sauceSetting"
        static let lettuceSetting = "lettuceSetting"
        static let tomatoSetting = "tomatoSetting"
        static let orderStatus = "orderStatus"
        static let orderLocation = "orderLocation"
        static let orderID = "orderID"
        
    }
    
    func insertIntoDatabase(){
        let currentUser = databaseRef.child(userID!)
        currentUser.child("name").setValue(name)
        let currentOrder = currentUser.child(orderID!)
        currentOrder.setValue(convToJason())
    }
    
    private func convToJason() -> [String : AnyObject] {
        let jsonObject: [String: AnyObject] = [
            DatabaseKeys.foodServing: foodServing as AnyObject,
            DatabaseKeys.bunSetting: bunSetting as AnyObject,
            DatabaseKeys.cheeseSetting: cheeseSetting as AnyObject,
            DatabaseKeys.sauceSetting: sauceSetting as AnyObject,
            DatabaseKeys.lettuceSetting: lettuceSetting as AnyObject,
            DatabaseKeys.tomatoSetting: tomatoSetting as AnyObject,
            DatabaseKeys.orderStatus: orderStatus as AnyObject,
            DatabaseKeys.orderLocation: orderLocation as AnyObject,
            DatabaseKeys.orderID: orderID as AnyObject,
        ]
        
        return jsonObject
    }
    
    /*class func dynamoDBTableName() -> String {

        return "yalegrill-mobilehub-1490068997-Orders"
    }
    
    class func hashKeyAttribute() -> String {
        return "email"
    }
    
    class func rangeKeyAttribute() -> String {

        return "orderID"
    }*/
    
    class func createNewObject(_userID: String,_name : String, _foodServing : String, _bunSetting : String, _cheeseSetting : String, _sauceSetting : String, _lettuceSetting : String, _tomatoSetting: String, _orderStatus : Int, _orderLocation: Int) -> Orders {
        let order = Orders()
        order.userID = _userID
        let uuid = CFUUIDCreateString(nil, CFUUIDCreate(nil))
        order.orderID = uuid as String?
        order.name = _name
        order.foodServing = _foodServing
        order.bunSetting = _bunSetting
        order.cheeseSetting = _cheeseSetting
        order.sauceSetting = _sauceSetting
        order.lettuceSetting = _lettuceSetting
        order.tomatoSetting = _tomatoSetting
        order.orderStatus = _orderStatus
        order.orderLocation = _orderLocation

        return order
    }
}
