//
//  Orders.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit
import AWSDynamoDB

class Orders: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var email: String?
    var orderNumber: NSNumber?
    var name: String?
    var foodServing: String?
    var bunSetting: String?
    var cheeseSetting: String?
    var sauceSetting: String?
    var lettuceSetting: String?
    var tomatoSetting: String?
    var isFinished: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "yalegrill-mobilehub-1490068997-Orders"
    }
    
    class func hashKeyAttribute() -> String {
        return "email"
    }
    
    class func rangeKeyAttribute() -> String {

        return "orderNumber"
    }
    
    class func returnNewRow(_email: String,_orderNum: Int,_name : String, _foodServing : String, _bunSetting : String, _cheeseSetting : String, _sauceSetting : String, _lettuceSetting : String, _tomatoSetting: String, _isFinished : NSNumber) -> Orders {
        let row = Orders()
        row?.email = _email
        row?.orderNumber = _orderNum as NSNumber?
        row?.name = _name
        row?.foodServing = _foodServing
        row?.bunSetting = _bunSetting
        row?.cheeseSetting = _cheeseSetting
        row?.sauceSetting = _sauceSetting
        row?.lettuceSetting = _lettuceSetting
        row?.tomatoSetting = _tomatoSetting
        row?.isFinished = _isFinished

        return row!
    }
}
